### ISSUE TITLE
Crash when adding user/work profile

### ISSUE THREAD

**Issue by benwalburn** [CyanogenMod/android_device_oneplus_oneplus3#14]
Settings crashes when I try to add a user. Attempting it again causes the system to hang until it reboots. Likewise, adding a work profile causes an error, then a crash on the next attempt. I'm pasting a bit of my logcat below.

> CryptdConnector: SND -> {10 cryptfs createnewuserdir 10 /data/user/10}
> 08-19 17:29:59.909   452   472 D VoldCryptCmdListener: cryptfs createnewuserdir
> 08-19 17:29:59.909   452   472 D Ext4Crypt: e4crypt_create_new_user_dir("10", "/data/user/10")
> 08-19 17:29:59.909 29464 29844 D CryptdConnector: RCV <- {200 10 -1}
> 08-19 17:29:59.910 29464 29942 E MountService: createnewuserdir sent unexpected message: -1
> 08-19 17:29:59.911 29464 29942 E JavaBinder: **\* Uncaught remote exception!  (Exceptions are not yet supported across processes.)
> 08-19 17:29:59.911 29464 29942 E JavaBinder: java.lang.RuntimeException: createnewuserdir sent unexpected message: -1
> 08-19 17:29:59.911 29464 29942 E JavaBinder:    at com.android.server.MountService.createNewUserDir(MountService.java:2649)
> 08-19 17:29:59.911 29464 29942 E JavaBinder:    at android.os.storage.StorageManager.createNewUserDir(StorageManager.java:965)
> 08-19 17:29:59.911 29464 29942 E JavaBinder:    at com.android.server.pm.UserManagerService.prepareUserDirectory(UserManagerService.java:1989)
> 08-19 17:29:59.911 29464 29942 E JavaBinder:    at com.android.server.pm.UserManagerService.createUserInternal(UserManagerService.java:1370)
> 08-19 17:29:59.911 29464 29942 E JavaBinder:    at com.android.server.pm.UserManagerService.createUser(UserManagerService.java:1311)
> 08-19 17:29:59.911 29464 29942 E JavaBinder:    at android.os.IUserManager$Stub.onTransact(IUserManager.java:65)
> 08-19 17:29:59.911 29464 29942 E JavaBinder:    at android.os.Binder.execTransact(Binder.java:453)
> 08-19 17:29:59.912 31134 31134 V JOAOMGCD: UI Action-New Input Action: Settings - 'OK' -
> 08-19 17:29:59.912 31134 31134 V JOAOMGCD: Point (x,y): 873,1237Focus;
> 08-19 17:29:59.916 29464 30001 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@25c3149 attribute=null, token = android.os.BinderProxy@a7071f0
> 08-19 17:29:59.916 30275  2559 E AndroidRuntime: FATAL EXCEPTION: Thread-64
> 08-19 17:29:59.916 30275  2559 E AndroidRuntime: Process: com.android.settings, PID: 30275
> 08-19 17:29:59.916 30275  2559 E AndroidRuntime: Theme: themes:{com.google.android.apps.inbox=overlay:com.pitchedapps.material.glass.free, default=overlay:com.blazze11.euphoria.dark, fontPkg:com.blazze11.euphoria.dark, com.android.systemui=overlay:com.blazze11.euphoria.dark, com.android.systemui.navbar=overlay:com.blazze11.euphoria.dark}
> 08-19 17:29:59.916 30275  2559 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'int android.content.pm.UserInfo.id' on a null object reference
> 08-19 17:29:59.916 30275  2559 E AndroidRuntime:        at com.android.settings.users.UserSettings$13.run(UserSettings.java:668)
> 08-19 17:29:59.918 29464 29942 W ActivityManager:   Force finishing activity com.android.settings/.SubSettings
> 08-19 17:29:59.924 31134 31134 V LASTMESSAGEn: Received last update com.joaomgcd.accessibility.a.e@6052989f
> 08-19 17:29:59.958  2545  2545 W System  : ClassLoader referenced unknown path: /data/app/com.Taptigo.ZoomFI-1/lib/arm64
> 08-19 17:29:59.966 29464 29490 W BroadcastQueue: Skipping deliver [background] BroadcastRecord{c835798 u-1 android.intent.action.BATTERY_CHANGED} to ReceiverList{da2510a 30275 com.android.settings/1000/u0 remote:a1fcd75}: process crashing
> 08-19 17:29:59.973 29464 29846 I Adreno  : QUALCOMM build                   : cababe8, I8a8f1b7e8f
> 08-19 17:29:59.973 29464 29846 I Adreno  : Build Date                       : 07/16/16
> 08-19 17:29:59.973 29464 29846 I Adreno  : OpenGL ES Shader Compiler Version: XE031.09.00.03
> 08-19 17:29:59.973 29464 29846 I Adreno  : Local Branch                     :
> 08-19 17:29:59.973 29464 29846 I Adreno  : Remote Branch                    :
> 08-19 17:29:59.973 29464 29846 I Adreno  : Remote Branch                    :
> 08-19 17:29:59.973 29464 29846 I Adreno  : Reconstruct Branch               :

**Comment by eternaleye** [comment]
I've been seeing this as well.
