### ISSUE TITLE
Updater not checking for new available versions

### ISSUE THREAD

**Issue by maciejstromich** [CyanogenMod/android_device_oneplus_oneplus3#29]
Hey team,

cmupdater is failing to get new cm14.1 versions with following error

```
11-20 02:01:41.562  7935  7935 D UpdateCheckService: Got update JSON data with 3 entries11-20 02:01:41.564  7935  7935 E UpdateCheckService: Error in JSON result
11-20 02:01:41.564  7935  7935 E UpdateCheckService: org.json.JSONException: Value null at api_level of type org.json.JSONObject$1 cannot be converted to int
11-20 02:01:41.564  7935  7935 E UpdateCheckService: 	at org.json.JSON.typeMismatch(JSON.java:100)
11-20 02:01:41.564  7935  7935 E UpdateCheckService: 	at org.json.JSONObject.getInt(JSONObject.java:481)
11-20 02:01:41.564  7935  7935 E UpdateCheckService: 	at com.cyanogenmod.updater.service.UpdateCheckService.parseUpdateJSONObject(UpdateCheckService.java:293)
11-20 02:01:41.564  7935  7935 E UpdateCheckService: 	at com.cyanogenmod.updater.service.UpdateCheckService.parseJSON(UpdateCheckService.java:276)
11-20 02:01:41.564  7935  7935 E UpdateCheckService: 	at com.cyanogenmod.updater.service.UpdateCheckService.onResponse(UpdateCheckService.java:320)
11-20 02:01:41.564  7935  7935 E UpdateCheckService: 	at com.cyanogenmod.updater.service.UpdateCheckService.onResponse(UpdateCheckService.java:316)
11-20 02:01:41.564  7935  7935 E UpdateCheckService: 	at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
11-20 02:01:41.564  7935  7935 E UpdateCheckService: 	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
11-20 02:01:41.564  7935  7935 E UpdateCheckService: 	at android.os.Handler.handleCallback(Handler.java:751)
11-20 02:01:41.564  7935  7935 E UpdateCheckService: 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-20 02:01:41.564  7935  7935 E UpdateCheckService: 	at android.os.Looper.loop(Looper.java:154)
11-20 02:01:41.564  7935  7935 E UpdateCheckService: 	at android.app.ActivityThread.main(ActivityThread.java:6088)
11-20 02:01:41.564  7935  7935 E UpdateCheckService: 	at java.lang.reflect.Method.invoke(Native Method)
11-20 02:01:41.564  7935  7935 E UpdateCheckService: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
11-20 02:01:41.564  7935  7935 E UpdateCheckService: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
11-20 02:01:41.566  7935  7935 I UpdateCheckService: The update check successfully completed at Sun Nov 20 02:01:41 GMT+01:00 2016 and found 0 updates (0 newer than installed)
```

**Comment by shyim** [comment]
Looks like fixed in the newer builds

**Comment by maciejstromich** [comment]
Yes, looks like it. I will close this issue.
